#!/usr/bin/env python
#  ScratchToCatrobat: A tool for converting Scratch projects into Catrobat programs.
#  Copyright (C) 2013-2015 The Catrobat Team
#  (<http://developer.catrobat.org/credits>)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  An additional term exception under section 7 of the GNU Affero
#  General Public License, version 3, is available at
#  http://developer.catrobat.org/license_additional_term
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function
import os
import platform
import subprocess
import sys
sys.path.append("./src")
from scratchtocatrobat.tools import helpers

data_dir = helpers.config.get("PATHS", "data")
log_dir = helpers.config.get("PATHS", "logging")
output_dir = helpers.config.get("PATHS", "output")
web_output_dir = helpers.config.get("PATHS", "web_output")
tmp_dir = helpers.config.get("PATHS", "tmp")

jython_home_dir = helpers.config.get("PATHS", "jython_home")
if not os.path.exists(jython_home_dir) or not os.path.isdir(jython_home_dir):
    error("Invalid jython home path given. No valid directory. Please update 'jython_home_dir' in the config file.")

jython_path = helpers.config.get("PATHS", "jython_exec")
if not os.path.exists(jython_path):
    error("Jython script path '%s' must exist." % jython_path.replace(".bat", "[.bat]"))

env = os.environ
env['JYTHONPATH'] = helpers.config.get("PATHS", "jython")

helpers.make_dir_if_not_exists(data_dir)
helpers.make_dir_if_not_exists(log_dir)
helpers.make_dir_if_not_exists(output_dir)
helpers.make_dir_if_not_exists(web_output_dir)
helpers.make_dir_if_not_exists(tmp_dir)

exec_args = [jython_path, "-m", "scratchtocatrobat.main"] + sys.argv[1:]
sys.exit(subprocess.call(exec_args, env=env))
