#!/bin/sh
# Squeakvm wrapper to load Scratch image.
#------------------------------------------------------------
cd squeak;
./scratch_squeak_vm \
-plugins Plugins/ \
-vm-sound-null \
-vm-display-null \
./ScratchSourceCode1.4.image "${@}"


