#!/bin/sh
# Squeakvm wrapper to load Scratch image.
#------------------------------------------------------------

./scratch_squeak_vm \
-plugins /usr/lib/scratch/Plugins \
-vm-sound-pulse \
./ScratchSourceCode1.4.image "${@}"


